name: digital_signer
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  logger: ^2.2.0
  shared_preferences: ^2.2.3
  jwt_decoder: ^2.0.1
  go_router: ^14.1.1
  file_picker: ^8.0.3
  path_provider: ^2.1.3
  dio: ^5.4.3+1
  font_awesome_flutter: ^10.7.0
  syncfusion_flutter_pdfviewer: ^25.2.5
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
